// source: srvRes.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var lsEnum_pb = require('./lsEnum_pb.js');
goog.object.extend(proto, lsEnum_pb);
var gameProto_pb = require('./gameProto_pb.js');
goog.object.extend(proto, gameProto_pb);
goog.exportSymbol('proto.lspb.SrvMsgType', null, global);
goog.exportSymbol('proto.lspb.SrvRes', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.lspb.SrvRes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, 500, null, null);
};
goog.inherits(proto.lspb.SrvRes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.lspb.SrvRes.displayName = 'proto.lspb.SrvRes';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.lspb.SrvRes.prototype.toObject = function(opt_includeInstance) {
  return proto.lspb.SrvRes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.lspb.SrvRes} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.lspb.SrvRes.toObject = function(includeInstance, msg) {
  var f, obj = {
    methodid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    result: jspb.Message.getFieldWithDefault(msg, 2, 0),
    errstr: jspb.Message.getFieldWithDefault(msg, 3, ""),
    srventerroom: (f = msg.getSrventerroom()) && gameProto_pb.SrvEnterRoom.toObject(includeInstance, f),
    srvinitover: (f = msg.getSrvinitover()) && gameProto_pb.SrvInitOver.toObject(includeInstance, f),
    bgameinit: (f = msg.getBgameinit()) && gameProto_pb.BGameInit.toObject(includeInstance, f),
    bgamestart: (f = msg.getBgamestart()) && gameProto_pb.BGameStart.toObject(includeInstance, f),
    bgameframe: (f = msg.getBgameframe()) && gameProto_pb.BGameFrame.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.lspb.SrvRes}
 */
proto.lspb.SrvRes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.lspb.SrvRes;
  return proto.lspb.SrvRes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.lspb.SrvRes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.lspb.SrvRes}
 */
proto.lspb.SrvRes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.lspb.SrvMsgType} */ (reader.readEnum());
      msg.setMethodid(value);
      break;
    case 2:
      var value = /** @type {!proto.lspb.Result} */ (reader.readEnum());
      msg.setResult(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setErrstr(value);
      break;
    case 101:
      var value = new gameProto_pb.SrvEnterRoom;
      reader.readMessage(value,gameProto_pb.SrvEnterRoom.deserializeBinaryFromReader);
      msg.setSrventerroom(value);
      break;
    case 102:
      var value = new gameProto_pb.SrvInitOver;
      reader.readMessage(value,gameProto_pb.SrvInitOver.deserializeBinaryFromReader);
      msg.setSrvinitover(value);
      break;
    case 1001:
      var value = new gameProto_pb.BGameInit;
      reader.readMessage(value,gameProto_pb.BGameInit.deserializeBinaryFromReader);
      msg.setBgameinit(value);
      break;
    case 1002:
      var value = new gameProto_pb.BGameStart;
      reader.readMessage(value,gameProto_pb.BGameStart.deserializeBinaryFromReader);
      msg.setBgamestart(value);
      break;
    case 1003:
      var value = new gameProto_pb.BGameFrame;
      reader.readMessage(value,gameProto_pb.BGameFrame.deserializeBinaryFromReader);
      msg.setBgameframe(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.lspb.SrvRes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.lspb.SrvRes.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.lspb.SrvRes} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.lspb.SrvRes.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMethodid();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getResult();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getErrstr();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getSrventerroom();
  if (f != null) {
    writer.writeMessage(
      101,
      f,
      gameProto_pb.SrvEnterRoom.serializeBinaryToWriter
    );
  }
  f = message.getSrvinitover();
  if (f != null) {
    writer.writeMessage(
      102,
      f,
      gameProto_pb.SrvInitOver.serializeBinaryToWriter
    );
  }
  f = message.getBgameinit();
  if (f != null) {
    writer.writeMessage(
      1001,
      f,
      gameProto_pb.BGameInit.serializeBinaryToWriter
    );
  }
  f = message.getBgamestart();
  if (f != null) {
    writer.writeMessage(
      1002,
      f,
      gameProto_pb.BGameStart.serializeBinaryToWriter
    );
  }
  f = message.getBgameframe();
  if (f != null) {
    writer.writeMessage(
      1003,
      f,
      gameProto_pb.BGameFrame.serializeBinaryToWriter
    );
  }
};


/**
 * optional SrvMsgType methodId = 1;
 * @return {!proto.lspb.SrvMsgType}
 */
proto.lspb.SrvRes.prototype.getMethodid = function() {
  return /** @type {!proto.lspb.SrvMsgType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.lspb.SrvMsgType} value
 * @return {!proto.lspb.SrvRes} returns this
 */
proto.lspb.SrvRes.prototype.setMethodid = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional Result result = 2;
 * @return {!proto.lspb.Result}
 */
proto.lspb.SrvRes.prototype.getResult = function() {
  return /** @type {!proto.lspb.Result} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.lspb.Result} value
 * @return {!proto.lspb.SrvRes} returns this
 */
proto.lspb.SrvRes.prototype.setResult = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional string errStr = 3;
 * @return {string}
 */
proto.lspb.SrvRes.prototype.getErrstr = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.lspb.SrvRes} returns this
 */
proto.lspb.SrvRes.prototype.setErrstr = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional SrvEnterRoom srvEnterRoom = 101;
 * @return {?proto.lspb.SrvEnterRoom}
 */
proto.lspb.SrvRes.prototype.getSrventerroom = function() {
  return /** @type{?proto.lspb.SrvEnterRoom} */ (
    jspb.Message.getWrapperField(this, gameProto_pb.SrvEnterRoom, 101));
};


/**
 * @param {?proto.lspb.SrvEnterRoom|undefined} value
 * @return {!proto.lspb.SrvRes} returns this
*/
proto.lspb.SrvRes.prototype.setSrventerroom = function(value) {
  return jspb.Message.setWrapperField(this, 101, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.lspb.SrvRes} returns this
 */
proto.lspb.SrvRes.prototype.clearSrventerroom = function() {
  return this.setSrventerroom(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.lspb.SrvRes.prototype.hasSrventerroom = function() {
  return jspb.Message.getField(this, 101) != null;
};


/**
 * optional SrvInitOver srvInitOver = 102;
 * @return {?proto.lspb.SrvInitOver}
 */
proto.lspb.SrvRes.prototype.getSrvinitover = function() {
  return /** @type{?proto.lspb.SrvInitOver} */ (
    jspb.Message.getWrapperField(this, gameProto_pb.SrvInitOver, 102));
};


/**
 * @param {?proto.lspb.SrvInitOver|undefined} value
 * @return {!proto.lspb.SrvRes} returns this
*/
proto.lspb.SrvRes.prototype.setSrvinitover = function(value) {
  return jspb.Message.setWrapperField(this, 102, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.lspb.SrvRes} returns this
 */
proto.lspb.SrvRes.prototype.clearSrvinitover = function() {
  return this.setSrvinitover(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.lspb.SrvRes.prototype.hasSrvinitover = function() {
  return jspb.Message.getField(this, 102) != null;
};


/**
 * optional BGameInit bGameInit = 1001;
 * @return {?proto.lspb.BGameInit}
 */
proto.lspb.SrvRes.prototype.getBgameinit = function() {
  return /** @type{?proto.lspb.BGameInit} */ (
    jspb.Message.getWrapperField(this, gameProto_pb.BGameInit, 1001));
};


/**
 * @param {?proto.lspb.BGameInit|undefined} value
 * @return {!proto.lspb.SrvRes} returns this
*/
proto.lspb.SrvRes.prototype.setBgameinit = function(value) {
  return jspb.Message.setWrapperField(this, 1001, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.lspb.SrvRes} returns this
 */
proto.lspb.SrvRes.prototype.clearBgameinit = function() {
  return this.setBgameinit(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.lspb.SrvRes.prototype.hasBgameinit = function() {
  return jspb.Message.getField(this, 1001) != null;
};


/**
 * optional BGameStart bGameStart = 1002;
 * @return {?proto.lspb.BGameStart}
 */
proto.lspb.SrvRes.prototype.getBgamestart = function() {
  return /** @type{?proto.lspb.BGameStart} */ (
    jspb.Message.getWrapperField(this, gameProto_pb.BGameStart, 1002));
};


/**
 * @param {?proto.lspb.BGameStart|undefined} value
 * @return {!proto.lspb.SrvRes} returns this
*/
proto.lspb.SrvRes.prototype.setBgamestart = function(value) {
  return jspb.Message.setWrapperField(this, 1002, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.lspb.SrvRes} returns this
 */
proto.lspb.SrvRes.prototype.clearBgamestart = function() {
  return this.setBgamestart(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.lspb.SrvRes.prototype.hasBgamestart = function() {
  return jspb.Message.getField(this, 1002) != null;
};


/**
 * optional BGameFrame bGameFrame = 1003;
 * @return {?proto.lspb.BGameFrame}
 */
proto.lspb.SrvRes.prototype.getBgameframe = function() {
  return /** @type{?proto.lspb.BGameFrame} */ (
    jspb.Message.getWrapperField(this, gameProto_pb.BGameFrame, 1003));
};


/**
 * @param {?proto.lspb.BGameFrame|undefined} value
 * @return {!proto.lspb.SrvRes} returns this
*/
proto.lspb.SrvRes.prototype.setBgameframe = function(value) {
  return jspb.Message.setWrapperField(this, 1003, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.lspb.SrvRes} returns this
 */
proto.lspb.SrvRes.prototype.clearBgameframe = function() {
  return this.setBgameframe(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.lspb.SrvRes.prototype.hasBgameframe = function() {
  return jspb.Message.getField(this, 1003) != null;
};


/**
 * @enum {number}
 */
proto.lspb.SrvMsgType = {
  ERRORSERVERTYPE: 0,
  SRVENTERROOM: 101,
  SRVINITOVER: 102,
  BGAMEINIT: 1001,
  BGAMESTART: 1002,
  BGAMEFRAME: 1003
};

goog.object.extend(exports, proto.lspb);
